on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: if0_37236217
        password: ${{ secrets.ftp_password }}
        port: 21
        protocol: ftp
        local-dir: ./
        server-dir: /http5225.kenyksze.com/htdocs/
